### ISSUE TITLE
Add an optional outgroup flag/option into the gubbins job generating script.

### ISSUE THREAD

**Issue by alipirani88** [alipirani88/variant_calling_pipeline#19]

**Comment by zmml** [comment]
I think this is working now.

**Comment by alipirani88** [comment]
any idea why this command is not working?
/nfs/esnitkin/bin_group/pipeline/Github/variant_calling_pipeline_dev/modules/variant_diagnostics/scripts/gubbins_iqtree_raxml.sh /scratch/esnitkin_fluxod/apirani/Project_Cdiff/Analysis/Project_propensity_score_match/2018_10_03_PSM_variant_calling///2019_01_10_15_50_07_core_results/gubbins/2019_01_10_15_50_07_cdiff_630_genome_aln_w_ref_allele.fa 1 'ERR232398'

**Comment by alipirani88** [comment]
I guess the script wont use esnitkin_flux as a default flux account.
