### ISSUE TITLE
Integrating variant QC script into the pipeline.

### ISSUE THREAD

**Issue by alipirani88** [alipirani88/variant_calling_pipeline#22]
- Package loading conflict issues: The packages used in the script conflicts with current flux R version. This could be solved by adding an additional step of automatically installed the required package or mention all the compatible package versions.
- Hard coded Path errors.

**Comment by zmml** [comment]
for flux: 
module load R/3.5.0 r-biomed-libs/3.5.0

changed to auto install packages - let me know if it works

**Comment by alipirani88** [comment]
> for flux:
> module load R/3.5.0 r-biomed-libs/3.5.0
> 
> changed to auto install packages - let me know if it works

I am getting a new error:

Quitting from lines 37-48 (variant_matrix_qc.spin.Rmd) 
Error in file(file, "rt") : cannot open the connection
Calls: <Anonymous> ... withVisible -> eval -> eval -> parse_snps -> read.table -> file
In addition: Warning messages:
1: In grDevices::png(f) :
  unable to load shared object '/sw/arcts/centos7/R/3.5.0/lib64/R/library/grDevices/libs//cairo.so':
  /lib64/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates
2: In grDevices::png(f) : failed to load cairo DLL

Execution halted

Running from: /nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices

Rscript /nfs/esnitkin/bin_group/pipeline/Github/variant_calling_pipeline/modules/variant_diagnostics/R_scripts/render_variant_matrix_qc.R SNP_matrix_allele_new.csv SNP_matrix_variant_qc

**Comment by alipirani88** [comment]
Quitting from lines 148-152 (/nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/tmp_SNP_matrix_variant_qc_SNP/variant_matrix_qc.spin.Rmd) 
Error in hclust(d, method = method) : 
  NA/NaN/Inf in foreign function call (arg 11)
Calls: <Anonymous> ... allele_heatmap -> pheatmap -> cluster_mat -> hclust
In addition: Warning messages:
1: In grDevices::png(f) :
  unable to load shared object '/sw/arcts/centos7/R/3.5.0/lib64/R/library/grDevices/libs//cairo.so':
  /lib64/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates
2: In grDevices::png(f) : failed to load cairo DLL
3: In (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  :
  failed to load cairo DLL

Execution halted

**Comment by zmml** [comment]
Coding SNP at 1406179 has too few lines in this file:
`/nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/SNP_matrix_code.csv`

**Comment by alipirani88** [comment]
@zmml The job finished with 100 % status but printed out an error and no html file.

/nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/SNP_matrix_variant_qc.o34092177

**Comment by alipirani88** [comment]
@zmml any idea what this error means?

/nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/SNP_matrix_variant_qc.e34100319

**Comment by alipirani88** [comment]
@zmml This is unresolved :)

**Comment by zmml** [comment]
When I tried running it, it worked:
/nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/2019-07-02_SNP_matrix_variant_qc_SNP_variant_matrix_qc.html

**Comment by alipirani88** [comment]
My module list:
 1) perl-modules/1.0   2) R/3.5.0   3) r-biomed-libs/3.5.0

**Comment by alipirani88** [comment]
I tried running the script without loading my environment and i get the same error:

processing file: /nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/tmp_SNP_matrix_variant_qc_SNP/variant_matrix_qc.spin.Rmd
output file: /nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/tmp_SNP_matrix_variant_qc_SNP/variant_matrix_qc.knit.md

pandoc: Could not find data file /nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/2019-07-16_SNP_matrix_variant_qc_SNP_variant_matrix_qc_files/figure-html/unnamed-chunk-10-1.svg
Error: pandoc document conversion failed with error 97
In addition: There were 17 warnings (use warnings() to see them)
Execution halted

/bin/pandoc +RTS -K512m -RTS /nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/tmp_SNP_matrix_variant_qc_SNP/variant_matrix_qc.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/2019-07-16_SNP_matrix_variant_qc_SNP_variant_matrix_qc.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /home/apirani/R/x86_64-pc-linux-gnu-library/3.5/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpkFuAgN/rmarkdown-str40b51e0f6855.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 

====
Script:
/nfs/esnitkin/Project_Bachman_Kleb/Sequence_data/consensus/R01_matched_cohort/2019_06_17_13_22_02_core_results/data_matrix/matrices/variant_qc_ap_v2.pbs
