### ISSUE TITLE
Indel row name issue? 

### ISSUE THREAD

**Issue by katiesaund** [alipirani88/variant_calling_pipeline#29]
I have the following rowname in my Cd ST2 indel matrix: 

`"Non-Coding Indel at 82614 > AATAGATT,AATAGATTATAGATTATAGATT,A,AATAGATTATAGATTATAGATTATAGATT,AATAGATTATAGATTATAGATTATAGATTATAGATT functional=NULL_NULL_NULL locus_tag=CWR55_RS00575-CWR55_RS00580 Strand Information: CWR55_RS00575=+/CWR55_RS00580=+/;AATAGATTATAGATTATAGATT|intergenic_region|MODIFIER|CWR55_RS00575-CWR55_RS00580|n.82614_82615insATAGATTATAGATTATAGATT||||CWR55_RS00575-CWR55_RS00580|CWR55_RS00575-CWR55_RS00580;A|intergenic_region|MODIFIER|CWR55_RS00575-CWR55_RS00580|n.82615_82621delATAGATT||||CWR55_RS00575-CWR55_RS00580|CWR55_RS00575-CWR55_RS00580;AATAGATTATAGATT|intergenic_region|MODIFIER|CWR55_RS00575-CWR55_RS00580|n.82614_82615insATAGATTATAGATT||||CWR55_RS00575-CWR55_RS00580|CWR55_RS00575-CWR55_RS00580;"`

It has 3 separate annotations: 1) AATAGATTATAGATTATAGATT, 2) A, and 3) AATAGATTATAGATT. 

However, the row contains 6 different alleles:  A, AATAGATT, AATAGATTATAGATT, AATAGATTATAGATTATAGATT, AATAGATTATAGATTATAGATTATAGATT, AATAGATTATAGATTATAGATTATAGATTATAGATT. 

Is the lack of annotations for the other alleles an issue with variant calling or generating the row name?

Relevant file: Line 76 of
`/nfs/esnitkin/Project_Cdiff/Sequence_data/U01_supplement_014_027_genomes/consensus/2018_08_15_U01_variant_sets/2019_09_26_U01_O14_ST2_Public_variant_calling/2019_11_18_11_18_56_core_results/data_matrix/matrices/Indel_matrix_allele.csv `

**Comment by alipirani88** [comment]
@katiesaund Could you test this matrix in your parser -/nfs/esnitkin/Project_Cdiff/Analysis/U01_supplement_014_027_genomes/2018_08_15_U01_variant_sets/2019_09_26_U01_O14_ST2_Public_variant_calling/core_temp_dir/Indel_matrix_allele.csv
