### ISSUE TITLE
Remove gene symbol and insert Locus Tag in field 4

### ISSUE THREAD

**Issue by alipirani88** [alipirani88/variant_calling_pipeline#30]
> sigK

> Change pipe-delimited field 4 to ALWAYS be locus tag, and NEVER gene symbol. Currently, the gene symbol is reported if there is a gene symbol, else the locus tag is reported.
> 
> Particularly when lines with multiple annotations are split on to separate row, this makes it impossible to cross reference the gene symbol to the strand information. In this case, I don't know what gene symbol sig K is.
> 
> "Coding SNP at 1431118 > C functional=NULL_NULL_NULL locus_tag=CD630_12310-CD630_12300 Strand Information: CD630_12310=-/CD630_12300=-/;C|missense_variant|MODERATE|CD630_12310|c.119A>G|p.Asn40Ser|119/1518|40/505|null or hypothetical protein,sigK|putative site-specific recombinase,Sigma K,;C|intron_variant|MODIFIER|sigK|c.391-1437A>G||||null or hypothetical protein,sigK|putative site-specific recombinase,Sigma K,;"
> 
> Also, sometimes the annotation is in pipe-delimited field 4 instead of locus tag or gene symbol
> "Non-Coding SNP at 5393980 > T functional=NULL_NULL_NULL locus_tag=KPNIH1_26385 Strand Information: KPNIH1_26385=-;T|intergenic_region|MODIFIER|KPNIH1_26385-null or hypothetical protein|n.5393980A>T||||null or hypothetical protein|hypothetical protein;"

Remove gene symbol and insert Locus Tag.

_Originally posted by @alipirani88 in https://github.com/alipirani88/variant_calling_pipeline/issues/15#issuecomment-540116128_

**Comment by alipirani88** [comment]
@sthiede do you remember which matrix was this. I wanted to test the fixes.

**Comment by sthiede** [comment]
i think this is the path to the C. diff matrix: 

'/nfs/esnitkin/Project_Cdiff/Sequence_data/Project_propensity_score_match/consensus/2019_04_12_11_45_07_core_results/data_matrix/matrices/SNP_matrix_code.csv'
